In [2]:
# import matplotlib.pyplot as plt
import numpy as np
import sys

from mlagents_envs.environment import UnityEnvironment
from mlagents_envs.side_channel.engine_configuration_channel import EngineConfig, EngineConfigurationChannel

import os
# print(os.getcwd())
# print(os.listdir(os.getcwd()))
import pandas as  pd

env_name = "D:/ml-agents-release-0.15.1/ml-agents-release-0.15.1/ml-agents-envs/Builds/UnityEnvironment"  # Name of the Unity environment binary to launch


In [60]:
engine_configuration_channel = EngineConfigurationChannel()
env = UnityEnvironment(file_name=env_name, side_channels = [engine_configuration_channel])
engine_configuration_channel.set_configuration_parameters(width = 2*160, height = 2*90, time_scale = 1, target_frame_rate = 2000)
env.reset()

UnityTimeOutException: The Unity environment took too long to respond. Make sure that :
	 The environment does not need user interaction to launch
	 The Agents are linked to the appropriate Brains
	 The environment and the Python interface have compatible versions.

In [59]:
group_name = env.get_agent_groups()
mode_freqs = np.zeros((4,3))


def tabulate_behavioral_modes():
    for p in range(step_result.n_agents()): #loop over each row INDEX down the obs[2]. The reason were doing this this way is that agent IDs is not necessarily preserved between episodes or time steps
        ID = np.where(onehotID[p,:]==1) #get ID of agent in this row
        item = np.where(item_carried[p,:] ==1) #get Item carried of agent in this row
#         print("ID" + str(ID) + "item" + str(item))
        mode_freqs[ID, item] += 1

for d in range(1000):
#         action_size = group_spec.action_size
#         branch_sizes = group_spec.discrete_action_branches
        env.step()
        step_result = env.get_step_result(group_name[0])
        
        item_carried = step_result.obs[2][:,3:6] 
        onehotID = step_result.obs[2][:,6:10]
        tabulate_behavioral_modes()
        
#         print(str(d) +  ' ' + str(step_result.agent_id[:]))
#         done = step_result.done[0]

print("mode frequencies: {}".format(mode_freqs))

mode frequencies: [[1001.    0.    0.]
 [1001.    0.    0.]
 [1001.    0.    0.]
 [1001.    0.    0.]]


step_result = env.get_step_result(group_name[0])

obs = step_result.obs[2][:,3:6]
onehotID = step_result.obs[2][:,6:10]

p=1
np.where(onehotID[p,:]==2)

In [46]:
step_result = env.get_step_result(group_name[0])

item_carried = step_result.obs[2][:,3:6] 
onehotID = step_result.obs[2][:,6:10]
def tabulate_behavioral_modes():
    for p in range(onehotID.shape[0]): #loop over each row INDEX down the obs[2]. The reason were doing this this way is that agent IDs is not necessarily preserved between episodes or time steps
        ID = np.where(onehotID[p,:]==1) #get ID of agent in this row
        item = np.where(item_carried[p,:] ==1) #get Item carried of agent in this row
        mode_freqs[ID, item] += 1
    return mode_freqs
# print(mode_freqs)

In [ ]:
env.close()

In [64]:
import pandas as pd
import numpy as np
# from sklearn.decomposition import PCA
# 
df_p = pd.read_csv("TAgent_1.csv", sep=',', header = None, engine='python')
print(df_p.loc[:,3:5].sum(axis = 0))
p_data = np.array(df_p)
print(p_data[:,3:6].sum(axis = 0))
# print(p_data)


3    1616.0
4    1050.0
5    1346.0
dtype: float64
[1616. 1050. 1346.]
